name: Build and deploy JAR app to Azure Web App

env:  
  JAVA_VERSION: '11'                  # set this to the Java version to use

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./src/FrontEnd/JavaWebAppValeyKey

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: java-app
      #     path: '${{ github.workspace }}/target/*.jar'

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: java-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: '*.jar'