name: Build and deploy JAR app to Azure Web App

env:  
  AZURE_WEBAPP_PACKAGE_PATH: ./src/FrontEnd/JavaWebAppValeyKey # set this to the path to your web app project
  JAVA_VERSION: '11'                  # set this to the Java version to use

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: microsoft
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: List directory
        run: ls
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target

      # - name: Azure Login
      #   uses: Azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ secrets.WEB_APP_NAME }}          
      #     package:  '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: java-app
      #     path: '${{ github.workspace }}/target/*.jar'

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: java-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: '*.jar'